version: "3"
services:
  sample:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app/:cached
      - ./sample/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - app
    working_dir: /var/www/app
    networks:
      internal-network:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app/:cached
    working_dir: /var/www/app
    networks:
      internal-network:

networks:
  internal-network:
    driver: bridge
